# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-11 08:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_detector'),
    ]

    operations = [
        migrations.AddField(
            model_name='detector',
            name='angle',
            field=models.IntegerField(default=0),
        ),
    ]
